### ISSUE TITLE
Empty datatip below the normal one

### ISSUE THREAD

**Issue by laughedelic** [atom-ide-community/atom-ide-signature-help#18]
I observe this artefact since I installed this package:

<img width="265" alt="Screenshot 2019-04-15 at 01 42 33" src="https://user-images.githubusercontent.com/766656/56102462-8a4d4e80-5f2d-11e9-895b-8b2e5b860352.png">
<img width="469" alt="Screenshot 2019-03-18 at 01 08 50" src="https://user-images.githubusercontent.com/766656/56102479-90dbc600-5f2d-11e9-849d-7fc1d2b76eaf.png">

I tried out changing the theme, but it didn't help. I suspect that it could be conflicting with the ide-ui package, but I don't know how to test or resolve it.

Atom 1.36 (was the same with 1.35).

**Comment by appelgriebsch** [comment]
Can you give me a link to a sample project to verify it? What Atom language | ide-package are you using?

**Comment by laughedelic** [comment]
I was using it with the [ide-scala](https://github.com/laughedelic/atom-ide-scala) package (I'm the author) for Scala development. But I just tried it on a typescript project and got the same result:

<img width="762" alt="Screenshot 2019-04-26 at 02 03 46" src="https://user-images.githubusercontent.com/766656/56775515-a079cb00-67c7-11e9-814c-85df0d3cc0fd.png">

This is from the atom-languageclient project.

**Comment by appelgriebsch** [comment]
Ok, I will have a look. Could you please check if you have disabled the data tip and signature help functionality from you ide-ui package after installing the replacements from the atom-ide-community?

**Comment by appelgriebsch** [comment]
Looks like having something to do with your setup... I've no ide-ui package installed; working just with the datatip and signature-help ones gives me that:

![image](https://user-images.githubusercontent.com/6803419/56789109-6f1df100-6801-11e9-8d22-3cfcd46e8b4c.png)
