### ISSUE TITLE
The overlay takes some space below the signature, and user cannot click there

### ISSUE THREAD

**Issue by aminya** [atom-ide-community/atom-ide-signature-help#49]
I hide the info bar for now, but we should fix this!

![image](https://user-images.githubusercontent.com/16418197/88319461-d31fb580-cce1-11ea-861a-a56efb7e6c31.png)

**Comment by aminya** [comment]
@UziTech @lierdakil any idea?

**Comment by aminya** [comment]
I finally found a fix for this.

**Comment by lierdakil** [comment]
Sorry, I was busy. The way I handled similar issues is by setting `pointer-events: none` CSS property.

**Comment by aminya** [comment]
Thank you! I fixed it by moving the parentElement (which is the atom-overlay) instead of my element.
